# Generated by Django 3.0.8 on 2021-01-01 15:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210101_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutionclassdetails',
            name='tution_class',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Nursery'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Inter-1st'), ('12', 'Inter-2nd'), ('13', 'Varsity Admission')], max_length=31, null=True),
        ),
    ]
