# Generated by Django 3.0.8 on 2021-01-01 16:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210101_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('employee', 'Employee'), ('employeer', 'Employeer')], max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tutionclassdetails',
            name='days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutionclassdetails',
            name='mediam',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bangla_mediam', 'Bangla Mediam'), ('english_mediam', 'English Mediam')], max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='tutionclassdetails',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutionclassdetails',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='accounts.Subject'),
        ),
        migrations.AlterField(
            model_name='tutionclassdetails',
            name='tutoring_place',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('class_room', 'Class Room'), ('Coaching_center', 'Coaching Center'), ('home_visit', 'Home Visit'), ('my_place', 'My Place')], max_length=46, null=True),
        ),
        migrations.AlterField(
            model_name='tutionclassdetails',
            name='tutoring_style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('group_tution', 'Group Tution'), ('privet_tution', 'Privet Tution')], max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='vedio',
            name='vedio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
